### ISSUE TITLE
TypeError when extracting all entries

### ISSUE THREAD

**Issue by crystaljgong** [melizalab/arfx#19] opened 2016-05-20 17:30 UTC
I get this error when trying to extract all entries from an arf file:

```
Traceback (most recent call last):
  File "//anaconda/bin/arfx", line 11, in <module>
    sys.exit(arfx())
  File "//anaconda/lib/python3.4/site-packages/arfx/arfx.py", line 578, in arfx
    args.op(args.arffile, entries, **opts)
  File "//anaconda/lib/python3.4/site-packages/arfx/arfx.py", line 287, in extract_entries
    dset = entry[channel]
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (-------src-dir--------/h5py/_objects.c:2582)
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (-------src-dir--------/h5py/_objects.c:2541)
  File "//anaconda/lib/python3.4/site-packages/h5py/_hl/dataset.py", line 462, in __getitem__
    selection = sel.select(self.shape, args, dsid=self.id)
  File "//anaconda/lib/python3.4/site-packages/h5py/_hl/selections.py", line 88, in select
    sel[args]
  File "//anaconda/lib/python3.4/site-packages/h5py/_hl/selections.py", line 356, in __getitem__
    if sorted(arg) != list(arg):
TypeError: unorderable types: numpy.ndarray() > str()
```

Running Python 3.4, arfx 2.2.3, and h5py 2.6.0

**Comment by dmeliza** [comment] 2021-02-27 00:10
Unable to reproduce; closing.

**Closed by dmeliza** 2021-02-27 00:10 UTC
